=== emazanch/XML/Schema.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Database of Health Insurance Company"
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="records" type="recType"/>
 
  <xsd:complexType name="recType">
     <xsd:sequence>
       <xsd:element name="client" type="clientType" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence> 
  </xsd:complexType>

   <xsd:complexType name="clientType">
     <xsd:sequence>
       <xsd:element name="demoData" type="demoType"/>
       <xsd:element name="adminData" type="adminType"/>
       <xsd:element name="riskStatus" type="riskStatusType"/>
       <xsd:element name="medHistory" type="medHistoryType"/>
       <xsd:element name="currentCondMngmt" type="currentCondMngType"/>
       <xsd:element name="outcomesData" type="outcomesDataType"/>
     </xsd:sequence>   
     <xsd:attribute name="id" use="required">
        <xsd:simpleType>
          <xsd:restriction base="xsd:integer">   
             <xsd:pattern value="[110-9]{5}"/>
          </xsd:restriction>
        </xsd:simpleType>
     </xsd:attribute>
     <xsd:attribute name="createdOn" type="xsd:date" use="required"/>
   </xsd:complexType>

   <xsd:complexType name="demoType">  
     <xsd:sequence>
       <xsd:element name="firstName" minOccurs="1" maxOccurs="unbounded">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">   
              <xsd:pattern value="[A-Z]*"/>
            </xsd:restriction>
          </xsd:simpleType>
       </xsd:element>
       <xsd:element name="lastName" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
       <xsd:choice>
          <xsd:element name="birthDate" type="xsd:date"/>
          <xsd:element name="birthYear" type="xsd:gYear"/>
       </xsd:choice>
       <xsd:element name="gender" type="genderType"/>
       <xsd:element name="maritalStatus" type="maritalType"/>
       <xsd:element name="address" type="xsd:string"/>
       <xsd:element name="city" type="xsd:string"/>
       <xsd:element name="zipcode" type="zCode"/>
       <xsd:element name="emergencyInfo" type="xsd:string"/>
     </xsd:sequence>   
   </xsd:complexType>

   <xsd:simpleType name="genderType">
     <xsd:restriction base="xsd:string">
        <xsd:pattern value="male|female"/>
     </xsd:restriction>
   </xsd:simpleType>

   <xsd:simpleType name="maritalType">
     <xsd:restriction base="xsd:string">
        <xsd:enumeration value="single"/>
        <xsd:enumeration value="married"/>
        <xsd:enumeration value="divorced"/>
        <xsd:enumeration value="widowed"/>
     </xsd:restriction>
   </xsd:simpleType>

   <xsd:simpleType name="zCode">
     <xsd:restriction base="xsd:integer">   
       <xsd:pattern value="\d{5}"/>
     </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="adminType">
     <xsd:sequence>
       <xsd:element name="contract" type="contractType"/>
       <xsd:element name="reqCopayment" type="xsd:string"/>
       <xsd:element name="benefitDeductibles" type="xsd:string"/>
       <xsd:element name="amountPaid" type="paidType"/>    
       <xsd:element name="provider" type="providerType"/>
     </xsd:sequence>   
   </xsd:complexType>

   <xsd:complexType name="paidType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:decimal">
        <xsd:attribute name="currency">
           <xsd:simpleType>
             <xsd:restriction base="xsd:string">
                <xsd:enumeration value="pounds"/>
                <xsd:enumeration value="euros"/>
                <xsd:enumeration value="dollars"/>
             </xsd:restriction>
           </xsd:simpleType>
        </xsd:attribute>  
      </xsd:extension>
    </xsd:simpleContent>
   </xsd:complexType>

   <xsd:simpleType name="contractType">
     <xsd:restriction base="xsd:string">
        <xsd:enumeration value="basic"/>
        <xsd:enumeration value="extended"/>
        <xsd:enumeration value="full coverage"/>
     </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="providerType">
     <xsd:sequence>
       <xsd:element name="practitionerType" type="xsd:string"/>  
       <xsd:element name="physicianSpec" type="xsd:string"/>   
       <xsd:element name="institutionNature" type="xsd:string"/>  
     </xsd:sequence>   
   </xsd:complexType>

   <xsd:complexType name="riskStatusType">
     <xsd:sequence>
       <xsd:element name="lifestyle" type="lifestyleType"/>
       <xsd:element name="antecedents" type="antecedentType"/>
       <xsd:element name="qualityOfLife" type="lifeQualType"/>
     </xsd:sequence>   
   </xsd:complexType>

   <xsd:complexType name="lifestyleType">
     <xsd:sequence>
       <xsd:element name="tobacco" type="yesNo"/>
       <xsd:element name="sport" type="yesNo"/>
     </xsd:sequence>  
   </xsd:complexType>

   <xsd:simpleType name="yesNo">
     <xsd:restriction base="xsd:string">
        <xsd:pattern value="yes|no"/>
     </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="antecedentType">
     <xsd:sequence>
       <xsd:element name="cancerFirstDegree" type="yesNo"/>
       <xsd:element name="cardiovascFirstDegree" type="yesNo"/>
       <xsd:element name="geneticFirstDegree" type="yesNo"/>
       <xsd:element name="others" type="xsd:string"/> 
     </xsd:sequence> 
   </xsd:complexType>

   <xsd:complexType name="lifeQualType">
     <xsd:sequence>
       <xsd:element name="physFunc" type="zeroTen"/>
       <xsd:element name="mentalFunc" type="zeroTen"/>         
       <xsd:element name="cognitiveFunc" type="zeroTen"/>       
       <xsd:element name="socialFunc" type="zeroTen"/> 
     </xsd:sequence>   
   </xsd:complexType>

   <xsd:simpleType name="zeroTen">
     <xsd:restriction base="xsd:integer">
        <xsd:minInclusive value="0"/> 
        <xsd:maxInclusive value="10"/>
     </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="medHistoryType">
     <xsd:sequence>
       <xsd:element name="hospAdmissions" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="surgeries" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="pregnancies" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="livebirth" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>  
   </xsd:complexType>

   <xsd:complexType name="currentCondMngType">
     <xsd:sequence>
       <xsd:element name="healthScreening" type="yesNo"/>    
       <xsd:element name="diagnoses" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="allergies" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="procedures" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="labTests" type="xsd:string"  minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="medPrescriptions" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
       <xsd:element name="counseling" type="xsd:string"  minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>
   </xsd:complexType>

   <xsd:simpleType name="outcomesDataType">
     <xsd:restriction base="xsd:string">
        <xsd:enumeration value="High-level of functioning and well-being"/>
        <xsd:enumeration value="Unexpected complications or side effect of care"/>
        <xsd:enumeration value="Readmission to hospital"/>
        <xsd:enumeration value="Death"/>
     </xsd:restriction>
   </xsd:simpleType>

</xsd:schema>

=== emazanch/XML/Doc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE records>

<records 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="Schema.xsd">

  <client id="11001" createdOn="2021-04-26"> 
    <demoData> <!-- Demographic data: -->
        <lastName>JOHNS</lastName>
        <firstName>Artur</firstName>
        <birthDate>1982-03-31</birthDate>
        <gender>male</gender>
        <maritalStatus>single</maritalStatus>
        <address>5 Rue Legendre</address>
        <city>Paris</city>
        <zipcode>75017</zipcode>
        <emergencyInfo>Eric Johns 01 05 45 39 98</emergencyInfo>
    </demoData>
    <adminData> <!-- Administrative data: -->
        <contract>basic</contract>
        <reqCopayment>yes</reqCopayment>
        <benefitDeductibles>no</benefitDeductibles>
        <amountPaid currency="euros">252.45</amountPaid>
        <provider>
            <practitionerType></practitionerType>
            <physicianSpec></physicianSpec>
            <institutionNature>public hospital</institutionNature>
        </provider>
    </adminData>
    <riskStatus> <!-- Health risks and health status: -->
        <lifestyle> <!-- Behavior and lifestyle -->
            <tobacco>no</tobacco>
            <sport>yes</sport>
        </lifestyle>
        <antecedents> <!-- Family history and genetic factors -->
            <cancerFirstDegree>no</cancerFirstDegree>
            <cardiovascFirstDegree>yes</cardiovascFirstDegree>
            <geneticFirstDegree>no</geneticFirstDegree>
            <others></others>
        </antecedents>
        <qualityOfLife> <!-- Health status (quality of life) -->
            <physFunc>8</physFunc>
            <mentalFunc>8</mentalFunc>
            <cognitiveFunc>8</cognitiveFunc>
            <socialFunc>6</socialFunc>
        </qualityOfLife>
    </riskStatus>
    <medHistory> <!-- Patient medical history:  -->
        <hospAdmissions>2</hospAdmissions>
        <surgeries>1</surgeries>
        <pregnancies></pregnancies>
        <livebirth></livebirth>
    </medHistory>
    <currentCondMngmt> <!-- Current management of health conditions: -->
        <healthScreening>yes</healthScreening>
        <diagnoses>back pain</diagnoses>
        <allergies>peanuts</allergies>
        <procedures></procedures>
        <labTests>Complete blood count</labTests>
        <labTests>XRay</labTests>
        <medPrescriptions>Antihistamine</medPrescriptions>
        <counseling></counseling>
    </currentCondMngmt>
    <outcomesData>High-level of functioning and well-being</outcomesData> <!-- Outcomes data: -->
  </client>
  
  <client id="11002" createdOn="2021-04-27"> 
    <demoData> <!-- Demographic data: -->
        <lastName>DUPOND</lastName>
        <firstName>Alice</firstName>
        <birthDate>1975-03-12</birthDate>
        <gender>female</gender>
        <maritalStatus>married</maritalStatus>
        <address>280 Rue Caroline</address>
        <city>Paris</city>
        <zipcode>75017</zipcode>
        <emergencyInfo>Serge Dupond 01 25 35 88 91</emergencyInfo>
    </demoData>
    <adminData> <!-- Administrative data: -->
        <contract>extended</contract>
        <reqCopayment>no</reqCopayment>
        <benefitDeductibles>no</benefitDeductibles>
        <amountPaid currency="euros">60.45</amountPaid>
        <provider>
            <practitionerType>Private practitioner</practitionerType>
            <physicianSpec>Sonographer</physicianSpec>
            <institutionNature></institutionNature>
        </provider>
    </adminData>
    <riskStatus> <!-- Health risks and health status: -->
        <lifestyle> <!-- Behavior and lifestyle -->
            <tobacco>no</tobacco>
            <sport>no</sport>
        </lifestyle>
        <antecedents> <!-- Family history and genetic factors -->
            <cancerFirstDegree>yes</cancerFirstDegree>
            <cardiovascFirstDegree>yes</cardiovascFirstDegree>
            <geneticFirstDegree>no</geneticFirstDegree>
            <others></others>
        </antecedents>
        <qualityOfLife> <!-- Health status (quality of life) -->
            <physFunc>5</physFunc>
            <mentalFunc>7</mentalFunc>
            <cognitiveFunc>7</cognitiveFunc>
            <socialFunc>7</socialFunc>
        </qualityOfLife>
    </riskStatus>
    <medHistory> <!-- Patient medical history:  -->
        <hospAdmissions>1</hospAdmissions>
        <surgeries></surgeries>
        <pregnancies>1</pregnancies>
        <livebirth>1</livebirth>
    </medHistory>
    <currentCondMngmt> <!-- Current management of health conditions: -->
        <healthScreening>yes</healthScreening>
        <diagnoses>Reflux esophagitis</diagnoses>
        <allergies>Penicilline</allergies>
        <procedures></procedures>
        <labTests>Complete blood count</labTests>
        <labTests>Echographie</labTests>
        <labTests>Pap test</labTests>
        <medPrescriptions></medPrescriptions>
        <counseling>Gastroenterologist</counseling>
    </currentCondMngmt>
    <outcomesData>High-level of functioning and well-being</outcomesData> <!-- Outcomes data: -->
  </client>

  <client id="11003" createdOn="2021-04-27"> 
    <demoData> <!-- Demographic data: -->
        <lastName>COSSIN</lastName>
        <firstName>Julie</firstName>
        <birthDate>1947-12-01</birthDate>
        <gender>female</gender>
        <maritalStatus>widowed</maritalStatus>
        <address>19 Rue du Capitaine Ferber</address>
        <city>Paris</city>
        <zipcode>75020</zipcode>
        <emergencyInfo></emergencyInfo>
    </demoData>
    <adminData> <!-- Administrative data: -->
        <contract>extended</contract>
        <reqCopayment>yes</reqCopayment>
        <benefitDeductibles>yes</benefitDeductibles>
        <amountPaid currency="euros">3650</amountPaid>
        <provider>
            <practitionerType>Surgeon</practitionerType>
            <physicianSpec></physicianSpec>
            <institutionNature>Private hospital</institutionNature>
        </provider>
    </adminData>
    <riskStatus> <!-- Health risks and health status: -->
        <lifestyle> <!-- Behavior and lifestyle -->
            <tobacco>yes</tobacco>
            <sport>no</sport>
        </lifestyle>
        <antecedents> <!-- Family history and genetic factors -->
            <cancerFirstDegree>no</cancerFirstDegree>
            <cardiovascFirstDegree>yes</cardiovascFirstDegree>
            <geneticFirstDegree>no</geneticFirstDegree>
            <others></others>
        </antecedents>
        <qualityOfLife> <!-- Health status (quality of life) -->
            <physFunc>3</physFunc>
            <mentalFunc>6</mentalFunc>
            <cognitiveFunc>6</cognitiveFunc>
            <socialFunc>4</socialFunc>
        </qualityOfLife>
    </riskStatus>
    <medHistory> <!-- Patient medical history:  -->
        <hospAdmissions>6</hospAdmissions>
        <surgeries>3</surgeries>
        <pregnancies>2</pregnancies>
        <livebirth>3</livebirth>
    </medHistory>
    <currentCondMngmt> <!-- Current management of health conditions: -->
        <healthScreening>no</healthScreening>
        <diagnoses>Hypertension</diagnoses>
        <diagnoses>Osteoarthritis</diagnoses>
        <diagnoses>Anxiety</diagnoses>
        <allergies>sulfamides</allergies>
        <procedures></procedures>
        <labTests>Blood cholesterol test</labTests>
        <labTests>Blood glucose test</labTests>
        <labTests>TSH test</labTests>
        <labTests>XRay</labTests>
        <medPrescriptions>Hypertension medications</medPrescriptions>
        <counseling>cardiologist</counseling>
    </currentCondMngmt>
    <outcomesData>Readmission to hospital</outcomesData> <!-- Outcomes data: -->
  </client>

  <client id="11005" createdOn="2021-04-28"> 
    <demoData> <!-- Demographic data: -->
        <lastName>BISLEAU</lastName>
        <firstName>Marc</firstName>
        <birthYear>1965</birthYear>
        <gender>male</gender>
        <maritalStatus>divorced</maritalStatus>
        <address>15 rue de Joyenval</address>
        <city>Chambourcy</city>
        <zipcode>78240</zipcode>
        <emergencyInfo>Michel Bisleau 02 04 56 33 12</emergencyInfo>
    </demoData>
    <adminData> <!-- Administrative data: -->
        <contract>full coverage</contract>
        <reqCopayment>yes</reqCopayment>
        <benefitDeductibles>yes</benefitDeductibles>
        <amountPaid currency="euros">186.35</amountPaid>
        <provider>
            <practitionerType>Hospitalist</practitionerType>
            <physicianSpec>trauma dept</physicianSpec>
            <institutionNature>public hospitel</institutionNature>
        </provider>
    </adminData>
    <riskStatus> <!-- Health risks and health status: -->
        <lifestyle> <!-- Behavior and lifestyle -->
            <tobacco>yes</tobacco>
            <sport>yes</sport>
        </lifestyle>
        <antecedents> <!-- Family history and genetic factors -->
            <cancerFirstDegree>no</cancerFirstDegree>
            <cardiovascFirstDegree>yes</cardiovascFirstDegree>
            <geneticFirstDegree>yes</geneticFirstDegree>
            <others></others>
        </antecedents>
        <qualityOfLife> <!-- Health status (quality of life) -->
            <physFunc>7</physFunc>
            <mentalFunc>6</mentalFunc>
            <cognitiveFunc>7</cognitiveFunc>
            <socialFunc>8</socialFunc>
        </qualityOfLife>
    </riskStatus>
    <medHistory> <!-- Patient medical history:  -->
        <hospAdmissions>3</hospAdmissions>
        <surgeries></surgeries>
        <pregnancies></pregnancies>
        <livebirth></livebirth>
    </medHistory>
    <currentCondMngmt> <!-- Current management of health conditions: -->
